(()=>{'use strict';const D=window.RESEARCH_DATA,L=window.ResearchLogic,$=s=>document.querySelector(s);const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(text,url)=>`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(text)} ↗</a>`;
for(let y=1996;y<=2025;y++){for(const id of ['#start-year','#end-year']){const op=document.createElement('option');op.value=y;op.textContent=y;$(id).append(op);}}$('#start-year').value=1996;$('#end-year').value=2025;
function showYear(r){document.querySelectorAll('.bar').forEach(el=>el.classList.toggle('selected',Number(el.dataset.year)===r.year));let note=r.notes||'執行人數，不是判決定讞人數。';if(r.year===2000)note+=' 交接年：17人尚未完整按執行日拆分，不分攤給兩位總統。';if(r.year<1999)note+=' 官方刊載學術研究，非已取得的原始統計年報。';$('#year-detail').innerHTML=`<strong>${r.year} 年 · ${r.executions} 人</strong><span>原表：${escape(r.source_raw_value)}</span><p>${escape(note)}</p><div>${link(r.source_locator,r.source_url)} · 查核 ${r.retrieved_at}</div>`;}
function draw(){const [start,end]=L.normalizeRange($('#start-year').value,$('#end-year').value);$('#start-year').value=start;$('#end-year').value=end;const rows=L.filterAnnual(D.annual.rows,start,end),s=L.summarize(rows);$('#range-summary').textContent=`${s.years}個完整曆年 · ${s.total}人 · 曆年平均${Number(s.average.toFixed(3))}人`;$('#annual-chart').innerHTML=rows.map(r=>`<div class="bar-cell"><button class="bar" data-year="${r.year}" style="height:${Math.max(1,r.executions/40*91)}%" aria-label="${r.year}年，${r.executions}人，查看來源"><span class="value">${r.executions}</span><span class="year">${r.year}</span></button></div>`).join('');const width=Math.max(420,rows.length*25);$('#annual-chart').style.minWidth=width+'px';$('#president-band').style.minWidth=width+'px';$('#president-band').innerHTML=L.periodSegments(D.periods,start,end).map(p=>`<div class="president-segment" style="left:${p.left}%;width:${p.width}%" title="${escape(p.president)}：${p.observed_start_inclusive}至${p.observed_end_exclusive}前">${escape(p.president)}</div>`).join('');document.querySelectorAll('.bar').forEach(el=>{const r=rows.find(r=>r.year===Number(el.dataset.year));el.addEventListener('click',()=>showYear(r));el.addEventListener('focus',()=>showYear(r));});showYear(rows.at(-1));}
$('#start-year').addEventListener('change',draw);$('#end-year').addEventListener('change',draw);$('#reset-years').addEventListener('click',()=>{$('#start-year').value=1996;$('#end-year').value=2025;draw();});draw();
const names={'Afghanistan':'阿富汗','China':'中國','Egypt':'埃及','Iran':'伊朗','Iraq':'伊拉克','Japan':'日本','Kuwait':'科威特','North Korea':'北韓','Saudi Arabia':'沙烏地阿拉伯','Singapore':'新加坡','Somalia':'索馬利亞','South Sudan':'南蘇丹','Taiwan':'台灣','United Arab Emirates':'阿拉伯聯合大公國','United States':'美國','Viet Nam':'越南','Yemen':'葉門'};
function renderGlobal(){$('#global-list').innerHTML=L.filterGlobal(D.global.records,$('#global-filter').value).map(r=>`<div class="global-item"><span>${names[r.country]}<small>${r.numeric_recorded===null?'確認執行，數量未知':r.status==='minimum'?'已知最低數':'來源紀錄值'}</small></span><strong>${escape(r.source_display)}</strong></div>`).join('');}$('#global-filter').addEventListener('change',renderGlobal);renderGlobal();
const menu=$('#menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);$('#nav').classList.toggle('is-open',open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');$('#nav').classList.remove('is-open');menu.focus();}});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('#nav').classList.remove('is-open');}));
const searchable=[...document.querySelectorAll('.searchable')].map((el,i)=>{if(!el.id)el.id='entry-'+i;return{el,text:el.textContent,title:el.querySelector('summary span,h3,h4')?.textContent||'研究段落'};});
let timer;function runSearch(){const q=$('#search').value.trim();$('#search-results').replaceChildren();if(!q){$('#search-status').textContent='搜尋論點、詳細說明與來源。輸入後會列出符合內容的段落。';return;}const hits=searchable.filter(x=>L.searchMatch(x.text,q));$('#search-status').textContent=`找到 ${hits.length} 個段落${hits.length>30?'；先列前30項':''}。`;if(!hits.length){$('#search-results').innerHTML='<p class="search-empty">沒有符合的段落。可試試較短關鍵字，例如「假釋」。</p>';return;}for(const hit of hits.slice(0,30)){const a=document.createElement('a');a.href='#'+hit.el.id;a.textContent=hit.title.trim();a.addEventListener('click',()=>{if(hit.el.tagName==='DETAILS')hit.el.open=true;let p=hit.el.parentElement;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}if(hit.el.classList.contains('source-item')){$('#source-filter').value='all';filterSources();}hit.el.classList.add('search-hit');setTimeout(()=>hit.el.classList.remove('search-hit'),2000);});$('#search-results').append(a);}}
$('#search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(runSearch,120);});$('#clear-search').addEventListener('click',()=>{$('#search').value='';runSearch();$('#search').focus();});
function filterSources(){const type=$('#source-filter').value;let count=0;document.querySelectorAll('.source-item').forEach(el=>{el.hidden=type!=='all'&&el.dataset.sourceType!==type;if(!el.hidden)count++;});$('#source-count').textContent=`顯示 ${count} 筆來源。`;}
$('#source-filter').addEventListener('change',filterSources);filterSources();
function revealHash(){if(!location.hash)return;const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(el){let p=el;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}}}window.addEventListener('hashchange',revealHash);revealHash();
})();
